### PR TITLE
Open in Visual Studio Code

### PR DESCRIPTION
**Pull request by Justinjdaniel**
Signed-off-by: Justin J Daniel <62233773+Justinjdaniel@users.noreply.github.com>

### CODE REVIEW

**Review by jt-nti — APPROVED** [review]
Looks good to me, thanks for the PR @Justinjdaniel

**Comment by jt-nti** [comment]
Unfortunately this PR broke the builds because .svg images are not allowed in the readme, so I'm going to revert it

**Comment by Justinjdaniel** [comment]
> Unfortunately this PR broke the builds because .svg images are not allowed in the readme, so I'm going to revert it

Should I change that to png and save it in the media directory?

**Comment by jt-nti** [comment]
Ideally there would be a `https://open.vscode.dev/badges/open-in-vscode.png` badge since this seems likely to be a common issue but I couldn't see a way to request that. Saving a png in the `media` directory seems like a reasonable alternative.

**Comment by Justinjdaniel** [comment]
Saved png in `media` directory and changes are made in `readme` file as well. Can you open this pull request again?

**Comment by jt-nti** [comment]
Hi @Justinjdaniel, I don't think I can reopen this PR because it was merged. Please could you open a new PR. Thanks

**Pull request merged**
