### PR TITLE
Duplicate word on paragraph 88

### PR DESCRIPTION
**Pull request by kant**
Signed-off-by: Darío Hereñu <magallania@gmail.com>

### CODE REVIEW

**Comment by heatherlp** [comment]
Hi @kant - thanks for contributing!
I've added some gotchas for readMe updates here, so please check them out: https://github.com/IBM-Blockchain/blockchain-vscode-extension/wiki/Developer-Tips#read-me-updates
Please can you also sign your commit?

**Comment by kant** [comment]
Applied the [Developer Certificate of Origin](https://probot.github.io/apps/dco/); I chose exclusively `blockchain-vscode-extension` and again did a pull-request.

**Comment by heatherlp** [comment]
Hi @kant, that doesn't seem to have worked, see details here: https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/971/checks?check_run_id=132828454
Please could you also update the other readMe? Details here: https://github.com/IBM-Blockchain/blockchain-vscode-extension/wiki/Developer-Tips#read-me-updates

Thanks

**Comment by cazfletch** [comment]
closing as no response

**Pull request closed without merging**
