### PR TITLE
Fixed wrong information in the tutorial

### PR DESCRIPTION
**Pull request by KorbinianK**
The tutorial mistakenly writes, that the user should right-click on `Smart Contracts` > `Installed` >`demoContract@0.0.1`. This is not possible, the correct way to upgrade is `Smart Contracts` > `Instantiated` >`demoContract@0.0.1`

Additionally I removed the second `1` that does not belong there.

### CODE REVIEW

**Comment by Jakeeyturner** [comment]
Hi @KorbinianK,

Thanks for creating a PR.
Would you be able to sign-off on your commit?

You can do this by running the following:
```
git commit --amend --signoff
git push origin patch-1 --force-with-lease
``` 

Thanks!

**Comment by KorbinianK** [comment]
@Jakeeyturner done :)

**Pull request merged**
